**Add functions**

In [ ]:
!pip install vecstack

In [ ]:
from vecstack import stacking
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score #works
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
#from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC
from collections import Counter #for Smote,

import warnings
warnings.filterwarnings("ignore")

**Add data files**

In [ ]:
#Read training data file

trainfile = r'/content/sample_data/RevisedHomesiteTrain1.csv'
train_data = pd.read_csv(trainfile)

print(train_data.shape)

print(train_data.head())

(65000, 596)
   CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
0                 2                 1               17               23   
1                 5                 9                6                8   
2                 4                 6                7               12   
3                15                23                3                2   
4                 4                 6                8               13   

   CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
0               17               23               15               22   
1                6                8                5                7   
2                7               12                6               10   
3                3                2                2                2   
4                8               13                7               11   

   CoverageField4A  CoverageField4B  ...  PropertyField38_N  \
0               16               2

In [ ]:
#Data Description
train_data.info()
train_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65000 entries, 0 to 64999
Columns: 596 entries, CoverageField11A to QuoteConversion_Flag
dtypes: float64(5), int64(591)
memory usage: 295.6 MB


CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
count      65000.000000      65000.000000     65000.000000     65000.000000   
mean           7.798892         12.954892         9.014585        12.995831   
std            5.304856          7.259023         5.586114         7.217093   
min           -1.000000         -1.000000        -1.000000        -1.000000   
25%            4.000000          7.000000         5.000000         7.000000   
50%            6.000000         13.000000         8.000000        13.000000   
75%           10.000000         19.000000        12.000000        19.000000   
max           25.000000         25.000000        25.000000        25.000000   

       CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
count     65000.000000     65000.000000     65000.000000     65000.000000   
mean          9.060000        13.017308         9.064538        13.017877   
std           5.568791         7.207118         5.588694         7.212825   
min           1.000000         1.000000         1.000000         1.000000   
25%           5.000000         7.000000         5.000000         7.000000   
50%           8.000000        13.000000         8.000000        13.000000   
75%          12.000000        19.000000        12.000000        19.000000   
max          25.000000        25.000000        25.000000        25.000000   

       CoverageField4A  CoverageField4B  ...  PropertyField38_N  \
count     65000.000000     65000.000000  ...       65000.000000   
mean          8.973785        13.011031  ...           0.974969   
std           5.564675         7.203325  ...           0.156220   
min           1.000000         1.000000  ...           0.000000   
25%           5.000000         7.000000  ...           1.000000   
50%           8.000000        13.000000  ...           1.000000   
75%          12.000000        19.000000  ...           1.000000   
max          25.000000        25.000000  ...           1.000000   

       PropertyField38_Y  GeographicField63_   GeographicField63_N  \
count       65000.000000              65000.0         65000.000000   
mean            0.020292                  0.0             0.976262   
std             0.140999                  0.0             0.152234   
min             0.000000                  0.0             0.000000   
25%             0.000000                  0.0             1.000000   
50%             0.000000                  0.0             1.000000   
75%             0.000000                  0.0             1.000000   
max             1.000000                  0.0             1.000000   

       GeographicField63_Y  GeographicField64_CA  GeographicField64_IL  \
count         65000.000000          65000.000000          65000.000000   
mean              0.023738              0.361862              0.120908   
std               0.152234              0.480543              0.326022   
min               0.000000              0.000000              0.000000   
25%               0.000000              0.000000              0.000000   
50%               0.000000              0.000000              0.000000   
75%               0.000000              1.000000              0.000000   
max               1.000000              1.000000              1.000000   

       GeographicField64_NJ  GeographicField64_TX  QuoteConversion_Flag  
count          65000.000000          65000.000000          65000.000000  
mean               0.267631              0.249600              0.188646  
std                0.442727              0.432785              0.391230  
min                0.000000              0.000000              0.000000  
25%                0.000000              0.000000              0.000000  
50%                0.000000              0.000000              0.000000  
75%                1.000000              0.000000              0.000000  
max                1.000000              1.000000              1.000000  

[8 rows x 596 columns]

In [ ]:
# To check number of null values
train_data.isna().sum()

CoverageField11A        0
CoverageField11B        0
CoverageField1A         0
CoverageField1B         0
CoverageField2A         0
                       ..
GeographicField64_CA    0
GeographicField64_IL    0
GeographicField64_NJ    0
GeographicField64_TX    0
QuoteConversion_Flag    0
Length: 596, dtype: int64

In [ ]:
testfile = r'/content/sample_data/RevisedHomesiteTest1.csv'
test_data = pd.read_csv(testfile)

print(test_data.shape)
print(test_data.head())

(173836, 596)
   CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
0                13                22                4                4   
1                 4                 5                8               14   
2                 3                 3               11               18   
3                 5                 9               14               22   
4                12                21                4                5   

   CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
0                4                4                3                3   
1                8               14                7               12   
2               11               18               10               16   
3               15               22               13               20   
4                4                5                4                4   

   CoverageField4A  CoverageField4B  ...  PropertyField38_N  \
0                3               

In [ ]:
#Data Description
test_data.info()
test_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173836 entries, 0 to 173835
Columns: 596 entries, CoverageField11A to GeographicField64
dtypes: float64(5), int64(590), object(1)
memory usage: 790.5+ MB


CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
count     173836.000000     173836.000000    173836.000000    173836.000000   
mean           7.793184         12.966060         9.018132        13.014893   
std            5.277834          7.235874         5.563241         7.204874   
min           -1.000000         -1.000000        -1.000000        -1.000000   
25%            4.000000          7.000000         5.000000         7.000000   
50%            6.000000         13.000000         8.000000        13.000000   
75%           10.000000         19.000000        12.000000        19.000000   
max           25.000000         25.000000        25.000000        25.000000   

       CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
count    173836.000000    173836.000000    173836.000000    173836.000000   
mean          9.063244        13.036494         9.061690        13.025231   
std           5.544948         7.195815         5.568419         7.194741   
min           1.000000         1.000000         1.000000         1.000000   
25%           5.000000         7.000000         5.000000         7.000000   
50%           8.000000        13.000000         8.000000        13.000000   
75%          12.000000        19.000000        12.000000        19.000000   
max          25.000000        25.000000        25.000000        25.000000   

       CoverageField4A  CoverageField4B  ...  PropertyField37_Y  \
count    173836.000000    173836.000000  ...      173836.000000   
mean          8.974223        13.030074  ...           0.288065   
std           5.540401         7.195347  ...           0.452863   
min           1.000000         1.000000  ...           0.000000   
25%           5.000000         7.000000  ...           0.000000   
50%           8.000000        13.000000  ...           0.000000   
75%          12.000000        19.000000  ...           1.000000   
max          25.000000        25.000000  ...           1.000000   

       PropertyField38_N  PropertyField38_Y  GeographicField63_   \
count      173836.000000      173836.000000        173836.000000   
mean            0.973164           0.021969             0.000006   
std             0.161603           0.146583             0.002398   
min             0.000000           0.000000             0.000000   
25%             1.000000           0.000000             0.000000   
50%             1.000000           0.000000             0.000000   
75%             1.000000           0.000000             0.000000   
max             1.000000           1.000000             1.000000   

       GeographicField63_N  GeographicField63_Y  GeographicField64_CA  \
count        173836.000000        173836.000000              173836.0   
mean              0.977099             0.022895                   0.0   
std               0.149588             0.149570                   0.0   
min               0.000000             0.000000                   0.0   
25%               1.000000             0.000000                   0.0   
50%               1.000000             0.000000                   0.0   
75%               1.000000             0.000000                   0.0   
max               1.000000             1.000000                   0.0   

       GeographicField64_IL  GeographicField64_NJ  GeographicField64_TX  
count              173836.0              173836.0              173836.0  
mean                    0.0                   0.0                   0.0  
std                     0.0                   0.0                   0.0  
min                     0.0                   0.0                   0.0  
25%                     0.0                   0.0                   0.0  
50%                     0.0                   0.0                   0.0  
75%                     0.0                   0.0                   0.0  
max                     0.0                   0.0                   0.0  

[8 rows x 595 columns]

In [ ]:
# To check number of null values
test_data.isna().sum()

CoverageField11A        0
CoverageField11B        0
CoverageField1A         0
CoverageField1B         0
CoverageField2A         0
                       ..
GeographicField64_CA    0
GeographicField64_IL    0
GeographicField64_NJ    0
GeographicField64_TX    0
QuoteConversion_Flag    0
Length: 596, dtype: int64

In [ ]:
#Combine Train and test for one Hot Encoding
combined_Data = pd.concat([train_data,test_data], keys=[0,1])

#Do one Hot encoding for categorical features
combined_Data["QuoteConversion_Flag"]=combined_Data["QuoteConversion_Flag"].map({1:1,0:0})
#combined_Data = pd.get_dummies(combined_Data,columns=categoricalFeatures)
print(combined_Data['QuoteConversion_Flag'])

#Separate Train data and test data
X_train = combined_Data.xs(0)
X_test = combined_Data.xs(1)
y_train=X_train["QuoteConversion_Flag"]
y_test=X_test["QuoteConversion_Flag"]
X_train1=X_train.iloc[:, :-1].copy()
X_test1=X_test.iloc[:, :-1].copy()

0  0        0
   1        0
   2        0
   3        0
   4        0
           ..
1  64995    0
   64996    0
   64997    0
   64998    0
   64999    0
Name: QuoteConversion_Flag, Length: 130000, dtype: int64


**ANALYSIS**

In [ ]:
#CONSTRUCT DEFAULT DECISION TREE AND OBTAIN RESPECTIVE ACCURACY
clf = DecisionTreeClassifier()
clf.fit(X_train1,y_train)
clf_predict=clf.predict(X_test1)
print("accuracy Score (training) for Decision Tree:{0:6f}".format(clf.score(X_test1,y_test)))
print("Confusion Matrix for Decision Tree")
print(confusion_matrix(y_test,clf_predict))

accuracy Score (training) for Decision Tree:1.000000
Confusion Matrix for Decision Tree
[[52738     0]
 [    0 12262]]


In [ ]:
#Hyperparameter tuning done for decision tree classifier
parameters={'min_samples_split' : range(10,100,10),'max_depth': range(1,20,2)}
clf_random = RandomizedSearchCV(clf,parameters,n_iter=15)
clf_random.fit(X_train1, y_train)
grid_parm=clf_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier
clf = DecisionTreeClassifier(**grid_parm)
clf.fit(X_train1,y_train)
clf_predict = clf.predict(X_test1)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for Decision Tree:{0:6f}".format(clf.score(X_test1,y_test)))
print("Confusion Matrix after hypertuning for Decision Tree")
print(confusion_matrix(y_test,clf_predict))
print("=== Classification Report ===")
print(classification_report(y_test,clf_predict))

#get cross-validation report
clf_cv_score = cross_val_score(clf, X_train1, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(clf_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Decision Tree: ",clf_cv_score.mean())

{'min_samples_split': 70, 'max_depth': 7}
accuracy Score (training) after hypertuning for Decision Tree:0.912231
Confusion Matrix after hypertuning for Decision Tree
[[52204   534]
 [ 5171  7091]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.91      0.99      0.95     52738
           1       0.93      0.58      0.71     12262

    accuracy                           0.91     65000
   macro avg       0.92      0.78      0.83     65000
weighted avg       0.91      0.91      0.90     65000

=== All AUC Scores ===
[0.94014684 0.93407408 0.92640534 0.93591612 0.9308617  0.93817566
 0.93840354 0.92828187 0.93814926 0.92667796]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree:  0.9337092354358258


In [ ]:
#Construct Random Forest Model

rfc = RandomForestClassifier()
rfc.fit(X_train1, y_train)
rfc_predict=rfc.predict(X_test1)
print("accuracy Score (training) for RandomForest:{0:6f}".format(rfc.score(X_test1,y_test)))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))

accuracy Score (training) for RandomForest:1.000000
Confusion Matrix for Random Forest:
[[52738     0]
 [    0 12262]]


In [ ]:
#Hyperparameter tuning for random forest classifier
rfc_random = RandomizedSearchCV(rfc,parameters,n_iter=15)
rfc_random.fit(X_train1, y_train)
grid_parm_rfc=rfc_random.best_params_
print(grid_parm_rfc)

#Construct Random Forest with best parameters
rfc= RandomForestClassifier(**grid_parm_rfc)
rfc.fit(X_train1,y_train)
rfc_predict = rfc.predict(X_test1)
print("accuracy Score (training) after hypertuning for Random Forest:{0:6f}".format(rfc.score(X_test1,y_test)))
print("Confusion Matrix after hypertuning for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,rfc_predict))

#get cross-validation report
rfc_cv_score = cross_val_score(rfc, X_train1, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())

{'min_samples_split': 10, 'max_depth': 19}
accuracy Score (training) after hypertuning for Random Forest:0.968477
Confusion Matrix after hypertuning for Random Forest:
[[52696    42]
 [ 2007 10255]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98     52738
           1       1.00      0.84      0.91     12262

    accuracy                           0.97     65000
   macro avg       0.98      0.92      0.95     65000
weighted avg       0.97      0.97      0.97     65000

=== All AUC Scores ===
[0.9496352  0.94859018 0.94048894 0.95162981 0.94861523 0.95313493
 0.95180287 0.9425898  0.95495219 0.94169093]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9483130065445124


In [ ]:
#Construct MultiLayer Perceptron Model
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(max_iter=100)
mlp.fit(X_train1, y_train)
mlp_predict=mlp.predict(X_test1)
print("accuracy Score (training) for MultiLayer Perceptron:{0:6f}".format(mlp.score(X_test1,y_test)))
print("Confusion Matrix for MultiLayer Perceptron:")
print(confusion_matrix(y_test,mlp_predict))

accuracy Score (training) for MultiLayer Perceptron:0.804723
Confusion Matrix for MultiLayer Perceptron:
[[43000  9738]
 [ 2955  9307]]


In [ ]:
#Hyperparameter tuning done for MultiLayer Perceptron classifier

#parameters = {'hidden_layer_sizes':[(10,), (20,)], 'activation':['tanh', 'relu'], 'solver':['sgd', 'adam'], 'alpha': [0.0001, 0.05], 'learning_rate':['constant', 'adaptive']}
#parameters = {'hidden_layer_sizes':[(10,5), (20,5)], 'activation':['tanh', 'relu'], 'learning_rate':['constant', 'adaptive']}
parameters = {'hidden_layer_sizes':[(10,5,3), (20,7,3)], 'activation':['tanh', 'relu'], 'learning_rate':['constant', 'adaptive'], 'max_iter' :[100, 150]}
#parameters = {'hidden_layer_sizes':[(10,), (15,), (10,5), (20,7,3)]}

mlp_random = RandomizedSearchCV(mlp,parameters,n_iter=15)
mlp_random.fit(X_train1, y_train)
grid_parm=mlp_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the MLPClassifier
mlp = MLPClassifier(**grid_parm)
mlp.fit(X_train1,y_train)
mlp_predict = mlp.predict(X_test1)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for MultiLayer Perceptron:{0:6f}".format(mlp.score(X_test1,y_test)))
print("Confusion Matrix after hypertuning for MultiLayer Perceptron")
print(confusion_matrix(y_test,mlp_predict))
print("=== Classification Report ===")
print(classification_report(y_test,mlp_predict))

#get cross-validation report
mlp_cv_score = cross_val_score(mlp, X_train1, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(mlp_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - MultiLayer Perceptron: ",mlp_cv_score.mean())


{'max_iter': 100, 'learning_rate': 'adaptive', 'hidden_layer_sizes': (10, 5, 3), 'activation': 'relu'}
accuracy Score (training) after hypertuning for MultiLayer Perceptron:0.811354
Confusion Matrix after hypertuning for MultiLayer Perceptron
[[52738     0]
 [12262     0]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.81      1.00      0.90     52738
           1       0.00      0.00      0.00     12262

    accuracy                           0.81     65000
   macro avg       0.41      0.50      0.45     65000
weighted avg       0.66      0.81      0.73     65000

=== All AUC Scores ===
[0.50097473 0.88474733 0.88615455 0.88115279 0.90607236 0.86006826
 0.5        0.5        0.5        0.64730344]


=== Mean AUC Score ===
Mean AUC Score - MultiLayer Perceptron:  0.7066473463493994


In [ ]:
#Construct K-Nearest Neighbor Model
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)

neigh.fit(X_train1, y_train)
neigh_predict=neigh.predict(X_test1)
print("accuracy Score (training) for KNeighborsClassifier:{0:6f}".format(neigh.score(X_test1,y_test)))
print("Confusion Matrix for KNeighborsClassifier:")
print(confusion_matrix(y_test,neigh_predict))

accuracy Score (training) for KNeighborsClassifier:0.853462
Confusion Matrix for KNeighborsClassifier:
[[50935  1803]
 [ 7722  4540]]


In [ ]:
#Hyperparameter tuning done for K-Nearest Neighbor classifier

parameters = {'n_neighbors':[3,5,7,9,11], 'weights':['uniform', 'distance'], 'p':[1,2]}


neigh_random = RandomizedSearchCV(neigh,parameters,n_iter=15)
neigh_random.fit(X_train1, y_train)
grid_parm=neigh_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the MLPClassifier
neigh = KNeighborsClassifier(**grid_parm)
neigh.fit(X_train1,y_train)
neigh_predict = neigh.predict(X_test1)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for KNeighborsClassifier:{0:6f}".format(neigh.score(X_test1,y_test)))
print("Confusion Matrix after hypertuning for KNeighborsClassifier")
print(confusion_matrix(y_test,neigh_predict))
print("=== Classification Report ===")
print(classification_report(y_test,neigh_predict))

#get cross-validation report
neigh_cv_score = cross_val_score(neigh, X_train1, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(neigh_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - KNeighborsClassifier: ",neigh_cv_score.mean())


In [ ]:
#Construct Linear Support Vector Machine Model
from sklearn.svm import LinearSVC
linsvm = LinearSVC(max_iter=300)
linsvm.fit(X_train1, y_train)
linsvm_predict=linsvm.predict(X_test1)
print("accuracy Score (training) for Linear SVM Classifier:{0:6f}".format(linsvm.score(X_test1,y_test)))
print("Confusion Matrix for Linear SVM Classifier:")
print(confusion_matrix(y_test,linsvm_predict))

accuracy Score (training) for Linear SVM Classifier:0.828815
Confusion Matrix for Linear SVM Classifier:
[[51895   843]
 [10284  1978]]


In [ ]:
#Construct Support Vector Machine Model
from sklearn.svm import SVC
svm = SVC(max_iter=500)
svm.fit(X_train1, y_train)
svm_predict=svm.predict(X_test1)
print("accuracy Score (training) for SVM Classifier:{0:6f}".format(svm.score(X_test1,y_test)))
print("Confusion Matrix for SVM Classifier:")
print(confusion_matrix(y_test,svm_predict))

accuracy Score (training) for SVM Classifier:0.515769
Confusion Matrix for SVM Classifier:
[[27621 25117]
 [ 6358  5904]]


In [ ]:
#Construct Gradient Boosting model

search_grid={'n_estimators':[5,10,20],'learning_rate':[0.01,.1]}
abc =GradientBoostingClassifier()
abc.fit(X_train1, y_train)
abc_predict=abc.predict(X_test1)
print("accuracy Score (training) for Boosting:{0:6f}".format(abc.score(X_test1,y_test)))
print("Confusion Matrix for boosting:")
print(confusion_matrix(y_test,abc_predict))
abc_random = RandomizedSearchCV(abc,search_grid,n_iter=15)
abc_random.fit(X_train1, y_train)
grid_parm_abc=abc_random.best_params_
print(grid_parm_abc)
abc= GradientBoostingClassifier(**grid_parm_abc)
abc.fit(X_train1,y_train)
abc_predict = abc.predict(X_test1)
print("accuracy Score (training) after hypertuning for Boosting:{0:6f}".format(abc.score(X_test1,y_test)))
print("Confusion Matrix after hypertuning for Boosting:")
print(confusion_matrix(y_test,abc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,abc_predict))
abc_cv_score = cross_val_score(abc, X_train1, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(abc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Boosting: ",abc_cv_score.mean())

In [ ]:
# Generate predictions for Kaggle submission
predictions = grid_search.best_estimator_.predict(X_test)
submission = pd.DataFrame({'Id': X_test.index, 'Prediction': predictions})
submission.to_csv('CIS508_GarimaAstha_Assignment3', index=False)

**SMOTE**

In [ ]:
print("___________________________________________________________________\nSMOTE\n")
print('Original dataset shape %s' % Counter(y_train))
sm = SMOTE(sampling_strategy='auto')
X_res, y_res = sm.fit_resample(X_train1, y_train)
print('Resampled dataset shape %s' % Counter(y_res))

___________________________________________________________________
SMOTE

Original dataset shape Counter({0: 52738, 1: 12262})
Resampled dataset shape Counter({0: 52738, 1: 52738})


**ensemble predictions (one-layer stacking)**

In [ ]:
# Import necessary libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score # Make sure to import accuracy_score if not already imported

print("___________________________________________________________________________________________\nEnsemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier\n")

models = [ KNeighborsClassifier(), MLPClassifier(), SVC(), LinearSVC(), RandomForestClassifier(), DecisionTreeClassifier() ]

S_Train, S_Test = stacking(models,
                           X_res, y_res, X_test1,
                           regression=False,

                           mode='oof_pred_bag',

                           needs_proba=False,

                           save_dir=None,

                           metric=accuracy_score,

                           n_folds=4,

                           stratified=True,

                           shuffle=True,

                           random_state=0,

                           verbose=2)


___________________________________________________________________________________________
Ensemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier

task:         [classification]
n_classes:    [2]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [6]

model  0:     [KNeighborsClassifier]
    fold  0:  [0.72808980]
    fold  1:  [0.72437332]
    fold  2:  [0.72600402]
    fold  3:  [0.72479047]
    ----
    MEAN:     [0.72581440] + [0.00144383]
    FULL:     [0.72581440]

model  1:     [MLPClassifier]
    fold  0:  [0.83078615]
    fold  1:  [0.87375327]
    fold  2:  [0.85938033]
    fold  3:  [0.87978308]
    ----
    MEAN:     [0.86092571] + [0.01891380]
    FULL:     [0.86092571]

model  2:     [SVC]
