**There are 4 stocks with normally distributed percentage returns.**
**The mean percentage returns by stock: 0.080, 0.095, 0.115, 0.145.**
**The return standard deviation by stock:  0.060, 0.080, 0.140, 0.195.**


**In any given year, the correlation among each pair of stocks follows:**
  - rho12 = 0.55, rho13 = 0.65, rho14 = 0.45
  - rho23 = 0.50, rho24 = 0.70
  - rho34 = 0.55

**Generate a sample of stock returns and compute the correlation coefficients for each pair of stocks in your sample.
**Check if they are close to the above correlations. The main task for the problem is to create the code that will generate the correlated random returns.**

In [ ]:
import numpy as np
import scipy.stats as stats

def generate_correlated_returns(means, std_devs, correlation_matrix, num_samples=10000):
    np.random.seed(42)  # For reproducibility

    # Compute covariance matrix
    covariance_matrix = np.outer(std_devs, std_devs) * correlation_matrix

    # Cholesky decomposition
    L = np.linalg.cholesky(covariance_matrix)

    # Generate independent standard normal variables
    uncorrelated = np.random.randn(num_samples, len(means))

    # Generate correlated normal variables
    correlated = uncorrelated @ L.T

    # Shift by means
    returns = correlated + means

    return returns

def compute_correlation_matrix(data):
    return np.corrcoef(data, rowvar=False)

# Given parameters
means = np.array([0.080, 0.095, 0.115, 0.145])
std_devs = np.array([0.060, 0.080, 0.140, 0.195])

correlation_matrix = np.array([
    [1.00, 0.55, 0.65, 0.45],
    [0.55, 1.00, 0.50, 0.70],
    [0.65, 0.50, 1.00, 0.55],
    [0.45, 0.70, 0.55, 1.00]
])

# Generate returns
sample_returns = generate_correlated_returns(means, std_devs, correlation_matrix)

# Compute and display correlation matrix
sample_correlation_matrix = compute_correlation_matrix(sample_returns)
print("Sample Correlation Matrix:")
print(sample_correlation_matrix)


Sample Correlation Matrix:
[[1.         0.55643572 0.64884769 0.44224308]
 [0.55643572 1.         0.50149561 0.69995896]
 [0.64884769 0.50149561 1.         0.54995435]
 [0.44224308 0.69995896 0.54995435 1.        ]]
